language: php

php:
  - 7.4
  - nightly

# faster builds on new travis setup not using sudo
sudo: false

matrix:
  allow_failures:
    - php: nightly

# cache vendor dirs
cache:
  directories:
    - vendor
    - $HOME/.composer/cache/files

# install dependencies
install:
  - composer self-update
  - composer install

script: composer test