language: php

php:
  - 7.4

# faster builds on new travis setup not using sudo
sudo: false

env:
  matrix:
    - PREFER_LOWEST="--prefer-lowest --prefer-stable"
    - PREFER_LOWEST=""

before_script:
  - composer update $PREFER_LOWEST

# cache vendor dirs
cache:
  directories:
    - vendor
    - $HOME/.composer/cache/files

# install dependencies
install:
  - composer self-update
  - composer update $COMPOSER_FLAGS --prefer-dist

script: composer test